### PR TITLE
Fix: _loopStyle bad configuration (fixes #62)

### LINKED ISSUE #62: Framework: _loopStyle must be explicitly set
### Subject of the issue
The _README.md_ [states](https://github.com/cgkineo/adapt-pageNav/blob/62dab8c6c8070f15012c964bc0b5257410cca153/README.md?plain=1#L37) that `_loopStyle` defaults to 'none'. In fact, if it's not set, it does not default to anything and the next/previous buttons are not shown at all. I would suggest that we default `_loopStyle` to 'none' if not set in the JSON.

https://github.com/cgkineo/adapt-pageNav/blob/62dab8c6c8070f15012c964bc0b5257410cca153/js/PageNavModel.js#L145

~~Also, the `siblings` option has recently been removed from the plugin. This should be removed from _example.json_ and _README.md_ for `_loopStyleComment`.~~

### Your environment
* Version: Framework (not AAT)
* Page Nav: 3.1.1

### Steps to reproduce
In a framework project (not AAT):

1. In the standard p101 that has a co-100 and co-200, add a Page Nav component to the first (co-100) topic.
2. Enable the `_root` and `_next` buttons.
3. Set `_loopStyle` to 'none' which should be the default.
4. Observe that the Next button is visible
5. Now, remove the `_loopStyle` line entirely from the Page Nav component config.
6. Observe that only the Main Menu button remains.

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #62 

### Fix
* Re-enable siblings looping as removed in [commit](https://github.com/cgkineo/adapt-pageNav/commit/7c8d86364f91816147a1fe3825a728e1b5204d94#diff-6c2ae9233aadf60cb19e106cb2fdffa44f13ef7e5d14e95b1ff2e666f791ae78L179-L181)
* Allow undefined or falsey config to render correctly

### CODE REVIEW

File: js/PageNavModel.js [hunk 1]
```diff
@@ -142,30 +142,16 @@ class PageNavModel extends ComponentModel {
...
-    if (loop) {
-      // Create a double copy to allow loop searching
+    const descendants = (loopStyle === 'allPages')
+      ? Adapt.course.getAllDescendantModels(true)
+      // For siblings and none
+      : this.getCurrentMenu().getAllDescendantModels(true);
+    const isLooping = Boolean(loopStyle && loopStyle !== 'none');
+    if (isLooping) {
+      // Create a double copy to allow loop searching to fall over the end
       descendants = descendants.concat(descendants);
```
Comment (swashbuck) [inline js/PageNavModel.js:152]: `descendents` should be declared as `let` since it is redefined here.

**Review by swashbuck — APPROVED** [review]
👍
