### PR TITLE
Fix: Check if content object(page) is set to _isOptional and unlock pageNav button if set to _lockUntilPageComplete (fixes #64)

### LINKED ISSUE #64: PageNav never unlocks when Page is _isOptional
### Subject of the issue
When the page is set as optional (a use case would be via something like the diagnostic plug-in) and PageNav is set to, _lockUntilPageComplete, PageNav remains locked - even after completing the topic. 

### Steps to reproduce
Install the diagnostic plug-in or set the page to isoptuional in the JSON

### Expected behaviour
The page would automatically unlock if the page is set to isOptional if _lockUntilPageComplete is set to true.

### Actual behaviour
Locked button never unlocks

### PR DESCRIPTION
**Pull request by StuartNicholls**
Fixes #64 

### Fix
Checks if content object(page) is set to _isOptional and automatically unlocks the pageNav buttons  to _lockUntilPageComplete 

### Testing
1. Install the diagnostic plug-in or set the Content Object to _isOptional
2. Configure pageNav to _lockUntilPageComplete

### CODE REVIEW

File: js/PageNavModel.js [hunk 1]
```diff
@@ -57,7 +58,7 @@ class PageNavModel extends ComponentModel {
         index: 0,
         order: order++,
         _tooltipId: `pagenav_btn${type}`,
-        locked: item._isLocked || (buttonConfig._lockUntilPageComplete && !currentPageComplete)
+        locked: (item._isLocked && !currentPageOptional) || ((buttonConfig._lockUntilPageComplete && !currentPageComplete) && !currentPageOptional)
```
Comment (oliverfoster) [inline js/PageNavModel.js:61]:
```suggestion
        locked: !currentPageOptional && (item._isLocked || (buttonConfig._lockUntilPageComplete && !currentPageComplete)) 
```

Comment (StuartNicholls) [reply js/PageNavModel.js:61]: Thanks, @oliverfoster ! I'll make myself a coffee x

**Review by oliverfoster — APPROVED** [review]

**Review by danielghost — APPROVED** [review]
