### PR TITLE
Fix: Ensure _customRouteId model is available before displaying button (fixes #71)

### LINKED ISSUE #71: Using _customRouteId skips _isAvailable check
### Subject of the issue
When using `_customRouteId`, there is no check to ensure that the content object is available (`_isAvailable: true`)

### PR DESCRIPTION
**Pull request by swashbuck**
Fix #71 

### Fix
* When using `_customRouteId`, ensure the content object model is available (`_isAvailable: true`). If not, do not display the button.
* This will still allow pages to be navigated to when they are hidden with `_isHidden: true`

### CODE REVIEW

**Review by oliverfoster — APPROVED** [review]

File: js/PageNavModel.js [hunk 1]
```diff
@@ -140,6 +140,12 @@ class PageNavModel extends ComponentModel {
     }
   }
 
+  getCustomRoutePage(id) {
+    const buttonModel = data.findById(id);
+    if (!buttonModel || !buttonModel.get('_isAvailable')) return;
```
Comment (oliverfoster) [inline js/PageNavModel.js:145]: `!buttonModel?.get?.('_isAvailable')` is how you do these
